# Pandas

### Pandas Stands for Panel Data and is the core library for data manipulation and data analysis

### It consists of single and multi-dimensional data-structures for data-manipulation

### Pandas Data-Structures

In [1]:
# 1 Single Dimensional is called series object 
# 2 Multi-Dimensional is called Data-Frame

In [2]:
import pandas as pd

### Series Object

In [3]:
s1 = pd.Series([1,2,3,4,5])

In [4]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(s1)

pandas.core.series.Series

In [6]:
s2 = pd.Series([1,2,3,4,5], index=[1,2,3,4,5])

In [7]:
s2

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [8]:
s3 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [9]:
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

### Series Object From Dictionary

In [10]:
s4 = pd.Series({"a":10,"b":20,"c":30})

In [11]:
s4

a    10
b    20
c    30
dtype: int64

In [12]:
s5 = pd.Series({"a":10,"b":20,"c":30}, index=["b","a","d","c"])

In [13]:
s5

b    20.0
a    10.0
d     NaN
c    30.0
dtype: float64

In [14]:
s5["a"]=54 # Changing Values

In [15]:
s5

b    20.0
a    54.0
d     NaN
c    30.0
dtype: float64

### Extracting Individual Elements

In [16]:
# Extracting a single Element

In [17]:
l1 = [10,20,30,40,50,60,70,80,90]

In [18]:
s6 = pd.Series(l1)
s6

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [19]:
s6[5]

60

In [20]:
# Extracting a sequence of Elements

In [21]:
s6[5:]

5    60
6    70
7    80
8    90
dtype: int64

In [22]:
s6[:5]

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [23]:
# Extracting elements from back

In [24]:
s6[-3:]

6    70
7    80
8    90
dtype: int64

In [25]:
s6[:-3]

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

### Maths operations on Series

In [26]:
s7 = pd.Series([1,2,3,4,5,6,7])

In [27]:
s7

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [28]:
s7 + 20

0    21
1    22
2    23
3    24
4    25
5    26
6    27
dtype: int64

In [29]:
s7 - 25

0   -24
1   -23
2   -22
3   -21
4   -20
5   -19
6   -18
dtype: int64

In [30]:
s8 = pd.Series([10,20,30,40,50,60,70])

In [31]:
s8

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [32]:
s7 + s8

0    11
1    22
2    33
3    44
4    55
5    66
6    77
dtype: int64

# Pandas DataFrame

## DataFrame is a 2- Dimenionsal labelled data-structure

### A data - frame comprises of rows and columns

In [33]:
d1 = pd.DataFrame({"Name":["Aditya","Sam","Jack"], "Marks": [100,20,30]})

In [34]:
d1

     Name  Marks
0  Aditya    100
1     Sam     20
2    Jack     30

In [35]:
d2 = pd.DataFrame({"Name":["Aditya","Sam","Jack"], "Marks": [100,20,30]},index=[1,2,3])

In [36]:
d2

     Name  Marks
1  Aditya    100
2     Sam     20
3    Jack     30

### DataFrame In-built Functions

In [37]:
iris = pd.read_csv("iris.csv") # Loading Dataset

In [38]:
iris.head() # This method is used to see the First Five Records

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
iris.tail() # This method is used to see the Last Five Records

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [40]:
iris.shape # To know Rows and Columns

(150, 5)

In [41]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### .iloc[ ]

In [42]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [43]:
iris.iloc[0:3,0:2] # This method is used to obtain records using index values

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [44]:
iris.iloc[25:35,2:4]

    petal_length  petal_width
25           1.6          0.2
26           1.6          0.4
27           1.5          0.2
28           1.4          0.2
29           1.6          0.2
30           1.6          0.2
31           1.5          0.4
32           1.5          0.1
33           1.4          0.2
34           1.5          0.2

In [45]:
iris.iloc[25:35,2:]

    petal_length  petal_width species
25           1.6          0.2  setosa
26           1.6          0.4  setosa
27           1.5          0.2  setosa
28           1.4          0.2  setosa
29           1.6          0.2  setosa
30           1.6          0.2  setosa
31           1.5          0.4  setosa
32           1.5          0.1  setosa
33           1.4          0.2  setosa
34           1.5          0.2  setosa

In [46]:
iris[0:10]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

### .loc[ ]

In [47]:
iris.loc[0:10,("sepal_length","petal_length")] # This method is also used to obtain records by their names
                                              # Here (0,10) is included

    sepal_length  petal_length
0            5.1           1.4
1            4.9           1.4
2            4.7           1.3
3            4.6           1.5
4            5.0           1.4
5            5.4           1.7
6            4.6           1.4
7            5.0           1.5
8            4.4           1.4
9            4.9           1.5
10           5.4           1.5

### Dropping Cloumns

In [48]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [49]:
iris.drop("sepal_length",axis=1) # Axis = 0 means Rows
                                 # Axis = 1 means Columns

     sepal_width  petal_length  petal_width    species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

### Dropping Rows

In [50]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [51]:
i1 = iris.drop([1,2,3], axis = 0)

In [52]:
i1

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [53]:
i2 = iris.drop(iris.index[1:10], axis = 0) # To Drop a Sequence

In [54]:
i2.head()

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa

### More Pandas Functions

In [55]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [56]:
iris.min()

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [57]:
iris.max()

sepal_length          7.9
sepal_width           4.4
petal_length          6.9
petal_width           2.5
species         virginica
dtype: object

In [58]:
iris.mean()

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [59]:
iris.median()

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [60]:
iris.std()

sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64

In [61]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [62]:
def half(s):
    return s*0.5

In [63]:
iris[["sepal_length","petal_length"]].apply(half) # Used to Apply something

     sepal_length  petal_length
0            2.55          0.70
1            2.45          0.70
2            2.35          0.65
3            2.30          0.75
4            2.50          0.70
..            ...           ...
145          3.35          2.60
146          3.15          2.50
147          3.25          2.60
148          3.10          2.70
149          2.95          2.55

[150 rows x 2 columns]

In [64]:
def double(s):
    return s*2

In [65]:
iris[["sepal_length","petal_length"]].apply(double)

     sepal_length  petal_length
0            10.2           2.8
1             9.8           2.8
2             9.4           2.6
3             9.2           3.0
4            10.0           2.8
..            ...           ...
145          13.4          10.4
146          12.6          10.0
147          13.0          10.4
148          12.4          10.8
149          11.8          10.2

[150 rows x 2 columns]

In [66]:
iris["species"].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [67]:
iris["petal_length"].value_counts()

1.5    13
1.4    13
5.1     8
4.5     8
1.6     7
1.3     7
5.6     6
4.0     5
4.9     5
4.7     5
5.0     4
1.7     4
4.8     4
4.4     4
4.2     4
4.1     3
5.7     3
5.5     3
6.1     3
3.9     3
4.6     3
5.8     3
5.2     2
1.9     2
6.0     2
1.2     2
4.3     2
5.3     2
5.4     2
3.3     2
6.7     2
3.5     2
5.9     2
3.6     1
3.8     1
1.0     1
3.0     1
6.3     1
6.6     1
3.7     1
1.1     1
6.4     1
6.9     1
Name: petal_length, dtype: int64

In [68]:
iris.sort_values(by = "sepal_length")

     sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [69]:
iris.sort_values(by = ["sepal_length","petal_length",])

     sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [70]:
iris.sort_index(axis = 0)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [71]:
iris.sort_index(axis = 1)

     petal_length  petal_width  sepal_length  sepal_width    species
0             1.4          0.2           5.1          3.5     setosa
1             1.4          0.2           4.9          3.0     setosa
2             1.3          0.2           4.7          3.2     setosa
3             1.5          0.2           4.6          3.1     setosa
4             1.4          0.2           5.0          3.6     setosa
..            ...          ...           ...          ...        ...
145           5.2          2.3           6.7          3.0  virginica
146           5.0          1.9           6.3          2.5  virginica
147           5.2          2.0           6.5          3.0  virginica
148           5.4          2.3           6.2          3.4  virginica
149           5.1          1.8           5.9          3.0  virginica

[150 rows x 5 columns]

In [72]:
iris[1:10].isnull()

   sepal_length  sepal_width  petal_length  petal_width  species
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False
5         False        False         False        False    False
6         False        False         False        False    False
7         False        False         False        False    False
8         False        False         False        False    False
9         False        False         False        False    False

In [73]:
iris.notnull()

     sepal_length  sepal_width  petal_length  petal_width  species
0            True         True          True         True     True
1            True         True          True         True     True
2            True         True          True         True     True
3            True         True          True         True     True
4            True         True          True         True     True
..            ...          ...           ...          ...      ...
145          True         True          True         True     True
146          True         True          True         True     True
147          True         True          True         True     True
148          True         True          True         True     True
149          True         True          True         True     True

[150 rows x 5 columns]

In [74]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [75]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [76]:
pd.set_option("display.max_columns",150)
pd.set_option("display.max_rows",150)

In [77]:
iris

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
5             5.4          3.9           1.7          0.4      setosa
6             4.6          3.4           1.4          0.3      setosa
7             5.0          3.4           1.5          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
10            5.4          3.7           1.5          0.2      setosa
11            4.8          3.4           1.6          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
13            4.3          3.0           1.1          0.1      setosa
14            5.8          4.0           1.2          0.2      setosa
15            5.7          4.4           1.5          0.4      setosa
16            5.4          3.9           1.3          0.4      setosa
17            5.1          3.5           1.4          0.3      setosa
18            5.7          3.8           1.7          0.3      setosa
19            5.1          3.8           1.5          0.3      setosa
20            5.4          3.4           1.7          0.2      setosa
21            5.1          3.7           1.5          0.4      setosa
22            4.6          3.6           1.0          0.2      setosa
23            5.1          3.3           1.7          0.5      setosa
24            4.8          3.4           1.9          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
26            5.0          3.4           1.6          0.4      setosa
27            5.2          3.5           1.5          0.2      setosa
28            5.2          3.4           1.4          0.2      setosa
29            4.7          3.2           1.6          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
31            5.4          3.4           1.5          0.4      setosa
32            5.2          4.1           1.5          0.1      setosa
33            5.5          4.2           1.4          0.2      setosa
34            4.9          3.1           1.5          0.2      setosa
35            5.0          3.2           1.2          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
37            4.9          3.6           1.4          0.1      setosa
38            4.4          3.0           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
40            5.0          3.5           1.3          0.3      setosa
41            4.5          2.3           1.3          0.3      setosa
42            4.4          3.2           1.3          0.2      setosa
43            5.0          3.5           1.6          0.6      setosa
44            5.1          3.8           1.9          0.4      setosa
45            4.8          3.0           1.4          0.3      setosa
46            5.1          3.8           1.6          0.2      setosa
47            4.6          3.2           1.4          0.2      setosa
48            5.3          3.7           1.5          0.2      setosa
49            5.0          3.3           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
55            5.7          2.8           4.5          1.3  versicolor
56            6.3          3.3           4.7          1.6  versicolor
57            4.9          2.4           3.3          1.0  versicolor
58            6.6          2.9           4.6          1.3  versicolor
59            5.2          2.7           3.9          1.4  versicolor
60            5.0          2.0           3.5          1.0  versicolor
61            5.9          3.0           4.2          1.5  versicolor
62            6.0          2.2           4.0          1.0  versicolor
63            6.1          2.9           4.7          1.4  versicolor
64            5.6          2.9           3.6          1.3  versicolor
65            6.7          3.1           4.4          1.4  versicolor
66            5.6          3.0           4.5          1.5  versicolor
67            5.8          2.7           4.1          1.0  versicolor
68            6.2          2.2           4.5          1.5  versicolor
69            5.6          2.5           3.9          1.1  versicolor
70            5.9          3.2           4.8          1.8  versicolor
71            6.1          2.8           4.0          1.3  versicolor
72            6.3          2.5           4.9          1.5  versicolor
73            6.1          2.8           4.7          1.2  versicolor
74            6.4          2.9           4.3          1.3  versicolor
75            6.6          3.0           4.4          1.4  versicolor
76            6.8          2.8           4.8          1.4  versicolor
77            6.7          3.0           5.0          1.7  versicolor
78            6.0          2.9           4.5          1.5  versicolor
79            5.7          2.6           3.5          1.0  versicolor
80            5.5          2.4           3.8          1.1  versicolor
81            5.5          2.4           3.7          1.0  versicolor
82            5.8          2.7           3.9          1.2  versicolor
83            6.0          2.7           5.1          1.6  versicolor
84            5.4          3.0           4.5          1.5  versicolor
85            6.0          3.4           4.5          1.6  versicolor
86            6.7          3.1           4.7          1.5  versicolor
87            6.3          2.3           4.4          1.3  versicolor
88            5.6          3.0           4.1          1.3  versicolor
89            5.5          2.5           4.0          1.3  versicolor
90            5.5          2.6           4.4          1.2  versicolor
91            6.1          3.0           4.6          1.4  versicolor
92            5.8          2.6           4.0          1.2  versicolor
93            5.0          2.3           3.3          1.0  versicolor
94            5.6          2.7           4.2          1.3  versicolor
95            5.7          3.0           4.2          1.2  versicolor
96            5.7          2.9           4.2          1.3  versicolor
97            6.2          2.9           4.3          1.3  versicolor
98            5.1          2.5           3.0          1.1  versicolor
99            5.7          2.8           4.1          1.3  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
106           4.9          2.5           4.5          1.7   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
113           5.7          2.5           5.0          2.0   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
119           6.0          2.2           5.0          1.5   virginica
120           6.9          3.2           5.7          2.3   virginica
121           5.6          2.8           4.9          2.0   virginica
122           7.7          2.8           6.7          2.0   virginica
123           6.3          2.7           4.9          1.8   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica
127           6.1          3.0           4.9          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
133           6.3          2.8           5.1          1.5   virginica
134           6.1          2.6           5.6          1.4   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
138           6.0          3.0           4.8          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

In [78]:
iris.sort_index(axis=1)

     petal_length  petal_width  sepal_length  sepal_width     species
0             1.4          0.2           5.1          3.5      setosa
1             1.4          0.2           4.9          3.0      setosa
2             1.3          0.2           4.7          3.2      setosa
3             1.5          0.2           4.6          3.1      setosa
4             1.4          0.2           5.0          3.6      setosa
5             1.7          0.4           5.4          3.9      setosa
6             1.4          0.3           4.6          3.4      setosa
7             1.5          0.2           5.0          3.4      setosa
8             1.4          0.2           4.4          2.9      setosa
9             1.5          0.1           4.9          3.1      setosa
10            1.5          0.2           5.4          3.7      setosa
11            1.6          0.2           4.8          3.4      setosa
12            1.4          0.1           4.8          3.0      setosa
13            1.1          0.1           4.3          3.0      setosa
14            1.2          0.2           5.8          4.0      setosa
15            1.5          0.4           5.7          4.4      setosa
16            1.3          0.4           5.4          3.9      setosa
17            1.4          0.3           5.1          3.5      setosa
18            1.7          0.3           5.7          3.8      setosa
19            1.5          0.3           5.1          3.8      setosa
20            1.7          0.2           5.4          3.4      setosa
21            1.5          0.4           5.1          3.7      setosa
22            1.0          0.2           4.6          3.6      setosa
23            1.7          0.5           5.1          3.3      setosa
24            1.9          0.2           4.8          3.4      setosa
25            1.6          0.2           5.0          3.0      setosa
26            1.6          0.4           5.0          3.4      setosa
27            1.5          0.2           5.2          3.5      setosa
28            1.4          0.2           5.2          3.4      setosa
29            1.6          0.2           4.7          3.2      setosa
30            1.6          0.2           4.8          3.1      setosa
31            1.5          0.4           5.4          3.4      setosa
32            1.5          0.1           5.2          4.1      setosa
33            1.4          0.2           5.5          4.2      setosa
34            1.5          0.2           4.9          3.1      setosa
35            1.2          0.2           5.0          3.2      setosa
36            1.3          0.2           5.5          3.5      setosa
37            1.4          0.1           4.9          3.6      setosa
38            1.3          0.2           4.4          3.0      setosa
39            1.5          0.2           5.1          3.4      setosa
40            1.3          0.3           5.0          3.5      setosa
41            1.3          0.3           4.5          2.3      setosa
42            1.3          0.2           4.4          3.2      setosa
43            1.6          0.6           5.0          3.5      setosa
44            1.9          0.4           5.1          3.8      setosa
45            1.4          0.3           4.8          3.0      setosa
46            1.6          0.2           5.1          3.8      setosa
47            1.4          0.2           4.6          3.2      setosa
48            1.5          0.2           5.3          3.7      setosa
49            1.4          0.2           5.0          3.3      setosa
50            4.7          1.4           7.0          3.2  versicolor
51            4.5          1.5           6.4          3.2  versicolor
52            4.9          1.5           6.9          3.1  versicolor
53            4.0          1.3           5.5          2.3  versicolor
54            4.6          1.5           6.5          2.8  versicolor
55            4.5          1.3           5.7          2.8  versicolor
56            4.7          1.6           6.3          3.3  versicolor
57            3.3          1.0           4.9          2.4  versicolor
58            4.6          1.3           6.6          2.9  versicolor
59            3.9          1.4           5.2          2.7  versicolor
60            3.5          1.0           5.0          2.0  versicolor
61            4.2          1.5           5.9          3.0  versicolor
62            4.0          1.0           6.0          2.2  versicolor
63            4.7          1.4           6.1          2.9  versicolor
64            3.6          1.3           5.6          2.9  versicolor
65            4.4          1.4           6.7          3.1  versicolor
66            4.5          1.5           5.6          3.0  versicolor
67            4.1          1.0           5.8          2.7  versicolor
68            4.5          1.5           6.2          2.2  versicolor
69            3.9          1.1           5.6          2.5  versicolor
70            4.8          1.8           5.9          3.2  versicolor
71            4.0          1.3           6.1          2.8  versicolor
72            4.9          1.5           6.3          2.5  versicolor
73            4.7          1.2           6.1          2.8  versicolor
74            4.3          1.3           6.4          2.9  versicolor
75            4.4          1.4           6.6          3.0  versicolor
76            4.8          1.4           6.8          2.8  versicolor
77            5.0          1.7           6.7          3.0  versicolor
78            4.5          1.5           6.0          2.9  versicolor
79            3.5          1.0           5.7          2.6  versicolor
80            3.8          1.1           5.5          2.4  versicolor
81            3.7          1.0           5.5          2.4  versicolor
82            3.9          1.2           5.8          2.7  versicolor
83            5.1          1.6           6.0          2.7  versicolor
84            4.5          1.5           5.4          3.0  versicolor
85            4.5          1.6           6.0          3.4  versicolor
86            4.7          1.5           6.7          3.1  versicolor
87            4.4          1.3           6.3          2.3  versicolor
88            4.1          1.3           5.6          3.0  versicolor
89            4.0          1.3           5.5          2.5  versicolor
90            4.4          1.2           5.5          2.6  versicolor
91            4.6          1.4           6.1          3.0  versicolor
92            4.0          1.2           5.8          2.6  versicolor
93            3.3          1.0           5.0          2.3  versicolor
94            4.2          1.3           5.6          2.7  versicolor
95            4.2          1.2           5.7          3.0  versicolor
96            4.2          1.3           5.7          2.9  versicolor
97            4.3          1.3           6.2          2.9  versicolor
98            3.0          1.1           5.1          2.5  versicolor
99            4.1          1.3           5.7          2.8  versicolor
100           6.0          2.5           6.3          3.3   virginica
101           5.1          1.9           5.8          2.7   virginica
102           5.9          2.1           7.1          3.0   virginica
103           5.6          1.8           6.3          2.9   virginica
104           5.8          2.2           6.5          3.0   virginica
105           6.6          2.1           7.6          3.0   virginica
106           4.5          1.7           4.9          2.5   virginica
107           6.3          1.8           7.3          2.9   virginica
108           5.8          1.8           6.7          2.5   virginica
109           6.1          2.5           7.2          3.6   virginica
110           5.1          2.0           6.5          3.2   virginica
111           5.3          1.9           6.4          2.7   virginica
112           5.5          2.1           6.8          3.0   virginica
113           5.0          2.0           5.7          2.5   virginica
114           5.1          2.4           5.8          2.8   virginica
115           5.3          2.3           6.4          3.2   virginica
116           5.5          1.8           6.5          3.0   virginica
117           6.7          2.2           7.7          3.8   virginica
118           6.9          2.3           7.7          2.6   virginica
119           5.0          1.5           6.0          2.2   virginica
120           5.7          2.3           6.9          3.2   virginica
121           4.9          2.0           5.6          2.8   virginica
122           6.7          2.0           7.7          2.8   virginica
123           4.9          1.8           6.3          2.7   virginica
124           5.7          2.1           6.7          3.3   virginica
125           6.0          1.8           7.2          3.2   virginica
126           4.8          1.8           6.2          2.8   virginica
127           4.9          1.8           6.1          3.0   virginica
128           5.6          2.1           6.4          2.8   virginica
129           5.8          1.6           7.2          3.0   virginica
130           6.1          1.9           7.4          2.8   virginica
131           6.4          2.0           7.9          3.8   virginica
132           5.6          2.2           6.4          2.8   virginica
133           5.1          1.5           6.3          2.8   virginica
134           5.6          1.4           6.1          2.6   virginica
135           6.1          2.3           7.7          3.0   virginica
136           5.6          2.4           6.3          3.4   virginica
137           5.5          1.8           6.4          3.1   virginica
138           4.8          1.8           6.0          3.0   virginica
139           5.4          2.1           6.9          3.1   virginica
140           5.6          2.4           6.7          3.1   virginica
141           5.1          2.3           6.9          3.1   virginica
142           5.1          1.9           5.8          2.7   virginica
143           5.9          2.3           6.8          3.2   virginica
144           5.7          2.5           6.7          3.3   virginica
145           5.2          2.3           6.7          3.0   virginica
146           5.0          1.9           6.3          2.5   virginica
147           5.2          2.0           6.5          3.0   virginica
148           5.4          2.3           6.2          3.4   virginica
149           5.1          1.8           5.9          3.0   virginica

In [79]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [80]:
iris

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
5             5.4          3.9           1.7          0.4      setosa
6             4.6          3.4           1.4          0.3      setosa
7             5.0          3.4           1.5          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
10            5.4          3.7           1.5          0.2      setosa
11            4.8          3.4           1.6          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
13            4.3          3.0           1.1          0.1      setosa
14            5.8          4.0           1.2          0.2      setosa
15            5.7          4.4           1.5          0.4      setosa
16            5.4          3.9           1.3          0.4      setosa
17            5.1          3.5           1.4          0.3      setosa
18            5.7          3.8           1.7          0.3      setosa
19            5.1          3.8           1.5          0.3      setosa
20            5.4          3.4           1.7          0.2      setosa
21            5.1          3.7           1.5          0.4      setosa
22            4.6          3.6           1.0          0.2      setosa
23            5.1          3.3           1.7          0.5      setosa
24            4.8          3.4           1.9          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
26            5.0          3.4           1.6          0.4      setosa
27            5.2          3.5           1.5          0.2      setosa
28            5.2          3.4           1.4          0.2      setosa
29            4.7          3.2           1.6          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
31            5.4          3.4           1.5          0.4      setosa
32            5.2          4.1           1.5          0.1      setosa
33            5.5          4.2           1.4          0.2      setosa
34            4.9          3.1           1.5          0.2      setosa
35            5.0          3.2           1.2          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
37            4.9          3.6           1.4          0.1      setosa
38            4.4          3.0           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
40            5.0          3.5           1.3          0.3      setosa
41            4.5          2.3           1.3          0.3      setosa
42            4.4          3.2           1.3          0.2      setosa
43            5.0          3.5           1.6          0.6      setosa
44            5.1          3.8           1.9          0.4      setosa
45            4.8          3.0           1.4          0.3      setosa
46            5.1          3.8           1.6          0.2      setosa
47            4.6          3.2           1.4          0.2      setosa
48            5.3          3.7           1.5          0.2      setosa
49            5.0          3.3           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
55            5.7          2.8           4.5          1.3  versicolor
56            6.3          3.3           4.7          1.6  versicolor
57            4.9          2.4           3.3          1.0  versicolor
58            6.6          2.9           4.6          1.3  versicolor
59            5.2          2.7           3.9          1.4  versicolor
60            5.0          2.0           3.5          1.0  versicolor
61            5.9          3.0           4.2          1.5  versicolor
62            6.0          2.2           4.0          1.0  versicolor
63            6.1          2.9           4.7          1.4  versicolor
64            5.6          2.9           3.6          1.3  versicolor
65            6.7          3.1           4.4          1.4  versicolor
66            5.6          3.0           4.5          1.5  versicolor
67            5.8          2.7           4.1          1.0  versicolor
68            6.2          2.2           4.5          1.5  versicolor
69            5.6          2.5           3.9          1.1  versicolor
70            5.9          3.2           4.8          1.8  versicolor
71            6.1          2.8           4.0          1.3  versicolor
72            6.3          2.5           4.9          1.5  versicolor
73            6.1          2.8           4.7          1.2  versicolor
74            6.4          2.9           4.3          1.3  versicolor
75            6.6          3.0           4.4          1.4  versicolor
76            6.8          2.8           4.8          1.4  versicolor
77            6.7          3.0           5.0          1.7  versicolor
78            6.0          2.9           4.5          1.5  versicolor
79            5.7          2.6           3.5          1.0  versicolor
80            5.5          2.4           3.8          1.1  versicolor
81            5.5          2.4           3.7          1.0  versicolor
82            5.8          2.7           3.9          1.2  versicolor
83            6.0          2.7           5.1          1.6  versicolor
84            5.4          3.0           4.5          1.5  versicolor
85            6.0          3.4           4.5          1.6  versicolor
86            6.7          3.1           4.7          1.5  versicolor
87            6.3          2.3           4.4          1.3  versicolor
88            5.6          3.0           4.1          1.3  versicolor
89            5.5          2.5           4.0          1.3  versicolor
90            5.5          2.6           4.4          1.2  versicolor
91            6.1          3.0           4.6          1.4  versicolor
92            5.8          2.6           4.0          1.2  versicolor
93            5.0          2.3           3.3          1.0  versicolor
94            5.6          2.7           4.2          1.3  versicolor
95            5.7          3.0           4.2          1.2  versicolor
96            5.7          2.9           4.2          1.3  versicolor
97            6.2          2.9           4.3          1.3  versicolor
98            5.1          2.5           3.0          1.1  versicolor
99            5.7          2.8           4.1          1.3  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
106           4.9          2.5           4.5          1.7   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
113           5.7          2.5           5.0          2.0   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
119           6.0          2.2           5.0          1.5   virginica
120           6.9          3.2           5.7          2.3   virginica
121           5.6          2.8           4.9          2.0   virginica
122           7.7          2.8           6.7          2.0   virginica
123           6.3          2.7           4.9          1.8   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica
127           6.1          3.0           4.9          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
133           6.3          2.8           5.1          1.5   virginica
134           6.1          2.6           5.6          1.4   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
138           6.0          3.0           4.8          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica